name: "Post to Mastodon"

on:
  workflow_dispatch:
  schedule:
    - cron: '14 */4 * * *'

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - run: npm ci
      - name: Do post
        run: node bot.js
        env:
          SOUNDCLOUD_CLIENT_ID: ${{ secrets.SOUNDCLOUD_CLIENT_ID }}
          SOUNDCLOUD_SECRET: ${{ secrets.SOUNDCLOUD_SECRET }}
          GOOGLE_TRANSLATE_API_KEY: ${{ secrets.GOOGLE_TRANSLATE_API_KEY }}
          SOUNDCLOUDSAID_BLUESKY_USERNAME: ${{ secrets.SOUNDCLOUDSAID_BLUESKY_USERNAME }}
          SOUNDCLOUDSAID_BLUESKY_PASSWORD: ${{ secrets.SOUNDCLOUDSAID_BLUESKY_PASSWORD }}
          SOUNDCLOUDSAID_MASTODON_ACCESS_TOKEN: ${{ secrets.SOUNDCLOUDSAID_MASTODON_ACCESS_TOKEN }}
          SOUNDCLOUDSAIDSOURCE_BLUESKY_USERNAME: ${{ secrets.SOUNDCLOUDSAIDSOURCE_BLUESKY_USERNAME }}
          SOUNDCLOUDSAIDSOURCE_BLUESKY_PASSWORD: ${{ secrets.SOUNDCLOUDSAIDSOURCE_BLUESKY_PASSWORD }}
          SOUNDCLOUDSAIDSOURCE_MASTODON_ACCESS_TOKEN: ${{ secrets.SOUNDCLOUDSAIDSOURCE_MASTODON_ACCESS_TOKEN }}

